name: sherlock
description: Collection of search and smart search functions, for local data and given priorities
version: 0.0.10
homepage: https://github.com/antoninhrlt/sherlock
license: MIT

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  diacritic: ^0.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
